### ISSUE TITLE
获取订单/用户的数量

### ISSUE THREAD

**Issue by j31234** [3C-Group/backend#17]
我蠢了＞﹏＜，部分获取订单/用户还需要知道总共有多少订单/用户。
希望添加以下API：
* 获取订单的总数量（也需要支持status, grouppk等filter下的总个数查询）
* 获取用户的总数量（也需要支持status, id等filter下的总个数查询）

**Comment by HeartyYF** [comment]
在 b9eed79 中实现了。现在拿到的数组中最后一个元素是数量，返回的是满足条件的全部数量，如果只获取了一部分也会返回全部的数量。
