### ISSUE TITLE
/manage/order/无法正确返回

### ISSUE THREAD

**Issue by Morehab** [3C-Group/backend#20]
例：
输入明天时段返回‘float() argument must be a string or a number, not 'datetime.timedelta'’
输入今天时段（提前4小时以前）返回‘begin time is in the past’

**Comment by HeartyYF** [comment]
第一个问题上周四修过了 因为这几天我们都比较忙 如果你用的是ry那边的后端她可能还没及时更新
第二个是只要begin time不晚于now+deltatime(hours=1)就会报的 我不确定正确的需求是什么

**Comment by HeartyYF** [comment]
已经完全好了
