### ISSUE TITLE
返回某个具体乐器在一个时间段内的所有可用时间和房间

### ISSUE THREAD

**Issue by Morehab** [3C-Group/backend#22]
传入：{userpk, instpk, begin_time, end_time}
返回：
时间段信息：{available: [{开始时间，结束时间}], unavailable: [{开始时间，结束时间，不可用原因}]}
房间信息：{available: [{名字，描述，pk}], unavailable: [{名字，描述，pk}]}
其中，时间段可用和房间可用都是在并集意义下的：
时间段可用当且仅当存在一个房间使它可用；
房间信息包括所有该乐器可能使用的房间，房间可用当且仅当在给定时间段内存在一个时间段使它可用

**Comment by HeartyYF** [comment]
> 时间段可用当且仅当存在一个房间使它可用
时间段可用为存在“至少”一个房间？

**Comment by Morehab** [comment]
yep

**Comment by HeartyYF** [comment]
这是两个api还是一个

**Comment by HeartyYF** [comment]
然后关于为啥不能用的原因可能很复杂，比如乐器维修同时房间也在维修，同时可能还没有权限，而且可能还检查到了禁用，咋办嘛

**Comment by Morehab** [comment]
一个吧，你拆成两个也行，问题不大

**Comment by HeartyYF** [comment]
糊了一下，目前在 api/get_inst_availablitiy/ 实现了这个功能。传入userpk, instpk, begin_time, end_time
传出available和unavailable是时间段，available_room和unavailable_room是房间
请检查一下对不对 不对的话我再改 对的话就close掉吧 我先去写文档

**Comment by Morehab** [comment]
ok

**Comment by Morehab** [comment]
postman上有了吗（

**Comment by HeartyYF** [comment]
有的，查询（用户，乐器）可用性，在查询房间和乐器类型两个下边
